const projectsList = [
  {
    id: 'project-1',
    title: 'E-Beer',
    description:
      'Responsive full-stack website for an e-commerce, that integrates both frontend and backend',
    category: ['web', 'ecommerce'],
    image: 'images/e-beer.png',
    stack: [
      'JavaScript',
      'React',
      'Node.js',
      'CSS',
      'HTML5',
      'Git',
      'SQL',
      'Jest',
      'Figma',
      'API rest',
      'Sequelize',
      'Postman',
    ],
    githubUrl: 'https://github.com/sofia-chiodi/grupo-13',
    demoUrl: '',
  },
  {
    id: 'project-2',
    title: 'Tic-tac-toe',
    description: 'Cute tic-tac-toe game',
    category: ['web', 'game'],
    image: 'images/tic-tac-toe.png',
    stack: ['JavaScript', 'React', 'Node.js', 'CSS', 'HTML5', 'Git', 'Vite'],
    githubUrl: 'https://github.com/sofia-chiodi/project-tictactoe',
    demoUrl: '',
  },
  {
    id: 'project-3',
    title: 'Quiz game',
    description: 'Music quiz game website',
    category: ['web', 'game'],
    image: 'images/quiz-game.png',
    stack: [
      'JavaScript',
      'React',
      'TypeScript',
      'TanStack Query',
      'Tailwind CSS',
      'Git',
      'Vite',
    ],
    githubUrl: 'https://github.com/sofia-chiodi/quiz',
    demoUrl: '',
  },
]

export default projectsList
